version: 2.0
jobs:
    test:
        steps:
            - checkout
            - run:
                name: check
                command: |
                    apt-get update
                    apt-get install -qy shellcheck
                    shellcheck *.sh

workflows:
  version: 2
  est:
    jobs:
        - test
